services:
  pp3-mysql:
    image: mysql:latest
    restart: always
    networks: 
      - pp3
    volumes:
      - ./var:/var/lib/mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: pp3
      MYSQL_PASSWORD: pp3
      MYSQL_DATABASE: pp3
  pp3-node:
    image: node:latest
    user: node
    working_dir: /home/node/app
    networks:
      - pp3
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    ports:
      - "3001:3001"
    command: >
      sh -c "rm -rf node_modules &&
             npm install &&
             npm run watch"
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - pp3-mysql
networks:
  pp3:
